name: Build

on:
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build React Client
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Install and Build Express Server
        working-directory: ./backend
        run: |
          npm ci
          npm run start
